---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list:
    - "recipe[build-essential::default]"
    - "recipe[mruby]"
  attributes:
    mruby:
      build_options:
        user_gems:
          -  [':git', 'https://github.com/iij/mruby-io.git']
- name: rbenv
  run_list:
    - "recipe[build-essential::default]"
    - "recipe[rbenv]"
    - "recipe[rbenv::ruby_build]"
    - "recipe[mruby::ruby_install]"
    - "recipe[mruby]"
  attributes:
    rbenv_ruby:
      user: root
      group: root
      root_path: "CONFIGURE_OPTS='--disable-install-doc' #{node[:rbenv][:install_prefix]}/rbenv"
    mruby:
      use_chef_ruby: false
