#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential'
cookbook 'rbenv'
cookbook 'apt'
cookbook 'nginx'
cookbook 'apache2'
cookbook 'mruby', :path => '../mruby'

